services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "10e"
      RAM_SIZE: "12G"
      CPU_CORES: "6"
      DISK_SIZE: "200G"
      USERNAME: "admin"
      PASSWORD: "1234567890"
    volumes:
      - /var/win:/storage
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
