services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "10e"
      USERNAME: "admin"
      PASSWORD: "1234567890"
  DHCP: "Y"
devices:
  - /dev/vhost-net
device_cgroup_rules:
  - 'c *:* rwm'
  networks:
      vlan:
        ipv4_address: 192.168.0.100

networks:
  vlan:
    external: true
    volumes:
      - /var/win:/storage
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_MODULE
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    restart: always
    stop_grace_period: 2m
