services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "10e"
      USERNAME: "admin"
      PASSWORD: "1234567890"
    volumes:
      - /var/win:/storage
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_MODULE
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
    volumes:
      - ./windows:/storage
    restart: always
    stop_grace_period: 2m
    docker network create -d macvlan \
    --subnet=192.168.0.0/24 \
    --gateway=192.168.0.1 \
    --ip-range=192.168.0.100/28 \
    -o parent=eth0 vlan
    device_cgroup_rules:
      - 'c *:* rwm'
    networks:
      pterodactyl_nw:
        ipv4_address: 172.18.0.7
