services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "10e"
      USERNAME: "admin"
      PASSWORD: "1234567890"
    volumes:
      - /var/win:/storage
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_MODULE
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    restart: always
    stop_grace_period: 2m
